server:
  port: 3344

spring:
  application:
    name: cloud-config-center

  cloud:
    config:
      server:
        git:
          uri: https://github.com/linshaozheng/springcloud-config.git
#          uri: https://gitee.com:jangkeo/springcloud-config.git
#          https://github.com/linshaozheng/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main

rabbitmq:
  host: 175.178.195.135
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - 'bus-refresh'


