server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.195.135:8848

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"